/*
1. DESARROLLE UNA SENTENCIA SELECT PARA CALCULAR EL IMPORTE DE LA PLANILLA DEL DEPARTAMENTO DE VENTAS. 
   DEBE INCLUIR EL SUELDO Y LA COMISION. ESQUEMAS SCOTT Y RH*/

SELECT SUM(SUELDO_TOTAL)PLANILLA_TOTAL FROM( 
SELECT S.*,(SAL+NVL(COMM,0))SUELDO_TOTAL FROM SCOTT.EMP S
WHERE DEPTNO='30'
) 

SELECT SUM(SUELDO_TOTAL)PLANILLA_TOTAL FROM( 
SELECT R.*,(SUELDO + NVL(COMISION,0))SUELDO_TOTAL FROM RECURSOS.EMPLEADO R
WHERE IDDEPARTAMENTO='103'
)
/*2*/
--RH
SELECT min(SUELDO)
FROM recursos.empleado WHERE IDDEPARTAMENTO = 103;

SELECT max(SUELDO)
FROM recursos.empleado WHERE IDDEPARTAMENTO = 103;



 SELECT	count(*) empleados,
		sum(sueldo) Planilla,
		avg(sueldo) "Sueldo PROMEDIO"
		FROM recursos.empleado
		WHERE iddepartamento = 102;

SELECT	count(*) empleados,
		sum(sueldo) Planilla,
		avg(sueldo) "Sueldo PROMEDIO"
		FROM scott.emp
		WHERE iddepartamento = 102;



--SCOTT

SELECT min(SAL)
FROM scott.emp WHERE DEPTNO = 30;

SELECT max(SAL)
FROM scott.emp WHERE DEPTNO = 30;
/*
4. SE NECESITA SABER LA CANTIDAD DE EMPLEADOS QUE HAY EN EL DEPARTAMENTO DE VENTAS.
   ESQUEMA SCCOT Y RH */

SELECT COUNT(ENAME) FROM SCOTT.EMP   
WHERE DEPTNO='30';

SELECT COUNT(NOMBRE) FROM RECURSOS.EMPLEADO R
WHERE IDDEPARTAMENTO='103'


/*
5. SE NECESITA SABER EL IMPORTE DE PLANILLA DEL DEPARTAMENTO DE VENTAS, CON COMISION Y SIN COMISION
   ESQUEMA SCCOT Y RH */
    
SELECT SUM(SAL) SIN_COMISION FROM SCOTT.EMP   
WHERE DEPTNO='30';

SELECT SUM((SAL+NVL(COMM,0)))CON_COMISION FROM SCOTT.EMP   
WHERE DEPTNO='30';
--------------------------------------------
SELECT SUM(SUELDO) SIN_COMISION FROM RECURSOS.EMPLEADO R
WHERE IDDEPARTAMENTO='103'

SELECT SUM((SUELDO + NVL(COMISION,0)))CON_COMISION FROM RECURSOS.EMPLEADO
WHERE IDDEPARTAMENTO='103'
   
/*
6. */

SELECT E.*, (CUR_VACANTES*CUR_PRECIO)MTO_RECAUDADO FROM EDUCA.CURSO E
WHERE CUR_ID='2';