--8. 
SELECT DEPTNO, AVG(SAL)PROMEDIO FROM SCOTT.EMP
GROUP BY DEPTNO;

SELECT IDDEPARTAMENTO, AVG(SUELDO)PROMEDIO FROM RECURSOS.EMPLEADO
GROUP BY IDDEPARTAMENTO;
--9
SELECT CUR_NOMBRE, SUM(CUR_PRECIO)
FROM EDUCA.CURSO
GROUP BY CUR_NOMBRE;


--13

SELECT DEPTNO,COUNT(ENAME),SUM(SAL),AVG(SAL) FROM SCOTT.EMP
GROUP BY DEPTNO;

SELECT IDDEPARTAMENTO,COUNT(IDEMPLEADO),SUM(SUELDO),AVG(SUELDO) FROM RECURSOS.EMPLEADO
GROUP BY IDDEPARTAMENTO;

--14
SELECT CUR_NOMBRE,CUR_MATRICULADOS,(CUR_MATRICULADOS*CUR_PRECIO)IMPOR_RECAU
FROM EDUCA.CURSO E