/*
15. Desarrolle una sentencia SELECT para encontrar 
	los departamentos que tienen a lo más de 3 
	trabajadores. Esquemas SCOTT y HR. */
SELECT 'SCOTT', DEPTNO, COUNT(1) CANTIDAD
FROM SCOTT.EMP
GROUP BY DEPTNO
HAVING COUNT(1) <= 3
UNION
SELECT 'RECURSOS', IDDEPARTAMENTO,  COUNT(1) CANTIDAD
FROM RECURSOS.EMPLEADO
GROUP BY IDDEPARTAMENTO
HAVING COUNT(1) <= 3

/*
16. Se necesita saber cuáles son los puestos de 
	trabajo que tienen más de 2 empleados.
	Esquemas SCOTT y HR */
SELECT d.DNAME NOMBRE, COUNT(e.EMPNO) CANTIDAD
FROM SCOTT.EMP e
INNER JOIN SCOTT.DEPT d ON d.DEPTNO = e.DEPTNO
GROUP BY D.DNAME
HAVING COUNT(*) > 2
UNION
SELECT  d.NOMBRE, COUNT(e.IDEMPLEADO) CANTIDAD
FROM RECURSOS.EMPLEADO e
INNER JOIN RECURSOS.DEPARTAMENTO d ON d.IDDEPARTAMENTO = e.IDDEPARTAMENTO
GROUP BY d.NOMBRE
HAVING count(*) > 2;

/*
17. Se necesita saber que empleados han registrado menor de 5 movimientos. Esquema 
EUREKA. 
*/
SELECT CHR_EMPLCODIGO, COUNT(1) CANTIDAD
FROM EUREKA.MOVIMIENTO
GROUP BY CHR_EMPLCODIGO
HAVING COUNT(1) < 5;

