--15.
SELECT IDDEPARTAMENTO, COUNT(*) EMPS,
SUM(SUELDO) PLANILLA
FROM recursos.empleado
GROUP BY IDDEPARTAMENTO
HAVING COUNT(*) < = 3;

SELECT IDDEPARTAMENTO, COUNT(*) FROM RECURSOS.EMPLEADO
GROUP BY IDDEPARTAMENTO
HAVING COUNT(*) < = 3;
--16.
SELECT JOB, COUNT(JOB) TOTAL FROM SCOTT.EMP
GROUP BY JOB
HAVING COUNT(JOB)>2

SELECT IDCARGO, COUNT(IDCARGO) TOTAL FROM RECURSOS.EMPLEADO
GROUP BY IDCARGO
HAVING COUNT(IDCARGO)>2
--17.
SELECT CHR_EMPLCODIGO, COUNT(CHR_EMPLCODIGO) TOTAL_MOV FROM EUREKA.MOVIMIENTO
GROUP BY CHR_EMPLCODIGO
HAVING COUNT(CHR_EMPLCODIGO)<  5