/*
DESARROLLAR UNA COINSULTA PARA OBTENER LOS SIGUIENTES DATOS DE LAS CUENTAS DE AHORRO
-NUMERO DE CUENTA
-SALDO
-NOMBRE DEL CLIENTE
-SUCURSAL
-NOMBRE DEL EMPLEADO QUE CREO LA CUENTA
-NOMBRE DE LA MONEDA
*/

SELECT CU.CHR_CUENCODIGO CTA,CU.DEC_CUENSALDO SALDO,
CL.VCH_CLIENOMBRE NCLIENTE,SU.VCH_SUCUNOMBRE SUCURSAL,
EM.VCH_EMPLNOMBRE NEMPLEADO,MO.VCH_MONEDESCRIPCION NMONEDA 
FROM EUREKA.CUENTA CU 
JOIN EUREKA.CLIENTE CL ON CL.CHR_CLIECODIGO = CU.CHR_CLIECODIGO
JOIN EUREKA.SUCURSAL SU ON CU.CHR_SUCUCODIGO = SU.CHR_SUCUCODIGO
JOIN EUREKA.EMPLEADO EM ON EM.CHR_EMPLCODIGO = CU.CHR_EMPLCREACUENTA 
JOIN EUREKA.MONEDA MO ON MO.CHR_MONECODIGO = CU.CHR_MONECODIGO;