
SELECT MT.CUR_ID "COD-CUR", 
CUR.CUR_NOMBRE NOMBRE, 
COUNT(MT.ALU_ID) ALUMNOS, 
SUM(MT.MAT_CUOTAS * MT.MAT_PRECIO) COMPROMISO,
SUM(NVL(PG.PAG_IMPORTE, 0)) RECAUDACION
FROM MATRICULA MT
INNER JOIN CURSO CUR ON CUR.CUR_ID = MT.CUR_ID
LEFT JOIN PAGO PG ON PG.ALU_ID = MT.ALU_ID AND PG.CUR_ID = MT.CUR_ID
GROUP BY MT.CUR_ID, CUR.CUR_NOMBRE 